/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaproject.MainUI;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author L3gend
 */
public class itemselect extends javax.swing.JFrame {

    /**
     * Creates new form itemselect
     */
    private DataHolder dataHolder;
    
    public itemselect() {    
        initComponents();
        imageload();  
        this.setBackground(new Color(0.0f,0.0f,0.0f,0.0f));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new customframework.PanelRound();
        jPanel1 = new javax.swing.JPanel();
        itemimglabel = new javax.swing.JLabel();
        itemlabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sugarcombobox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        icecombobox = new javax.swing.JComboBox<>();
        addbtn = new customframework.Button();
        ventibtn = new customframework.ButtonCircle();
        tallbtn = new customframework.ButtonCircle();
        shortbtn = new customframework.ButtonCircle();
        grandebtn = new customframework.ButtonCircle();
        jLabel13 = new javax.swing.JLabel();
        totalpricelabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        toppingcombobox = new javax.swing.JComboBox<>();
        closebtn = new javax.swing.JLabel();
        maximizebtn = new javax.swing.JLabel();
        minimizebtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        itemimglabel.setToolTipText("");

        itemlabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        itemlabel.setText("jLabel16");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(itemimglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemimglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(itemlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Size Options");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("What's included");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Short");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Tall");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Grande");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Venti");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("8 fl oz");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("12 fl oz");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("16 fl oz");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("20 fl oz");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Sugar");

        sugarcombobox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sugarcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "25%", "50%" }));
        sugarcombobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sugarcomboboxItemStateChanged(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Ice");

        icecombobox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        icecombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Ice", "Less Ice", "Normal" }));

        addbtn.setBackground(new java.awt.Color(102, 255, 0));
        addbtn.setText("Add");
        addbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbtnMouseClicked(evt);
            }
        });

        ventibtn.setFocusable(false);
        ventibtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ventibtnMouseClicked(evt);
            }
        });

        tallbtn.setFocusable(false);
        tallbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tallbtnMouseClicked(evt);
            }
        });

        shortbtn.setFocusable(false);
        shortbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shortbtnMouseClicked(evt);
            }
        });

        grandebtn.setFocusable(false);
        grandebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grandebtnMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Total Price -");

        totalpricelabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        totalpricelabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        totalpricelabel.setText("0");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Choose topping");

        toppingcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Milk Pudding", "Coconut Jelly", "Fruit Jelly", "Bubble", "Coffee Jelly" }));
        toppingcombobox.setPreferredSize(new java.awt.Dimension(99, 27));
        toppingcombobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                toppingcomboboxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shortbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(tallbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(grandebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ventibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(totalpricelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(sugarcombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(icecombobox, 0, 200, Short.MAX_VALUE)
                                .addComponent(toppingcombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(51, 51, 51))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ventibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tallbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shortbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grandebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sugarcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(icecombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toppingcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalpricelabel)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        closebtn.setBackground(new java.awt.Color(255, 255, 255));
        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setFocusable(false);
        closebtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closebtn.setOpaque(true);
        closebtn.setPreferredSize(new java.awt.Dimension(400, 300));
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closebtnMouseExited(evt);
            }
        });

        maximizebtn.setBackground(new java.awt.Color(255, 255, 255));
        maximizebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maximizebtn.setOpaque(true);
        maximizebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maximizebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maximizebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maximizebtnMouseExited(evt);
            }
        });

        minimizebtn.setBackground(new java.awt.Color(255, 255, 255));
        minimizebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizebtn.setOpaque(true);
        minimizebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizebtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addGap(275, 655, Short.MAX_VALUE)
                        .addComponent(minimizebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maximizebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maximizebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimizebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public String cupsizelabel;
    public String itemname;
    public Integer qty;
    public Integer getid;
    public Integer baseprice;
    
    private void ventibtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventibtnMouseClicked
        // TODO add your handling code here:            
        cupsizelabel = "Venti";
        cupsizecolor();
        priceload();
    }//GEN-LAST:event_ventibtnMouseClicked

    private void grandebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grandebtnMouseClicked
        // TODO add your handling code here:
        cupsizelabel ="Grande";
        cupsizecolor();
        priceload();
    }//GEN-LAST:event_grandebtnMouseClicked

    private void tallbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tallbtnMouseClicked
        // TODO add your handling code here:
        cupsizelabel ="Tall";
        cupsizecolor();
        priceload();
    }//GEN-LAST:event_tallbtnMouseClicked

    private void shortbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shortbtnMouseClicked
        // TODO add your handling code here:      
        cupsizelabel = "Short";
        cupsizecolor();
        priceload();
    }//GEN-LAST:event_shortbtnMouseClicked

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closebtnMouseClicked

    private void closebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseEntered
        // TODO add your handling code here:
        closebtn.setBackground(new Color(220,0,0,255));

        ImageIcon closeicon = new ImageIcon(this.getClass().getResource("../icon/whiteclose.png"));
        Image logoclose = closeicon.getImage();
        Image scaleclose = logoclose.getScaledInstance(15,15,Image.SCALE_SMOOTH);
        ImageIcon scaledclose = new ImageIcon(scaleclose);
        closebtn.setIcon(scaledclose);
    }//GEN-LAST:event_closebtnMouseEntered

    private void closebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseExited
        // TODO add your handling code here:
        closebtn.setBackground(Color.WHITE);

        ImageIcon closeicon = new ImageIcon(this.getClass().getResource("../icon/close.png"));
        Image logoclose = closeicon.getImage();
        Image scaleclose = logoclose.getScaledInstance(15,15,Image.SCALE_SMOOTH);
        ImageIcon scaledclose = new ImageIcon(scaleclose);
        closebtn.setIcon(scaledclose);
    }//GEN-LAST:event_closebtnMouseExited
    private boolean maximizestate;
    private void maximizebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizebtnMouseClicked
        // TODO add your handling code here:
        if(maximizestate){
            this.setExtendedState(this.NORMAL);

            ImageIcon maximizeicon = new ImageIcon(this.getClass().getResource("../icon/maximize.png"));
            Image logomaximize = maximizeicon.getImage();
            Image scalemaximize = logomaximize.getScaledInstance(15,15,Image.SCALE_SMOOTH);
            ImageIcon scaledmaximize = new ImageIcon(scalemaximize);
            maximizebtn.setIcon(scaledmaximize);
        }else{
            this.setExtendedState(this.MAXIMIZED_BOTH);

            ImageIcon maximizeicon = new ImageIcon(this.getClass().getResource("../icon/restore.png"));
            Image logomaximize = maximizeicon.getImage();
            Image scalemaximize = logomaximize.getScaledInstance(15,15,Image.SCALE_SMOOTH);
            ImageIcon scaledmaximize = new ImageIcon(scalemaximize);
            maximizebtn.setIcon(scaledmaximize);
        }
        maximizestate = !maximizestate;
    }//GEN-LAST:event_maximizebtnMouseClicked

    private void maximizebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizebtnMouseEntered
        // TODO add your handling code here:
        maximizebtn.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_maximizebtnMouseEntered

    private void maximizebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizebtnMouseExited
        // TODO add your handling code here:
        maximizebtn.setBackground(Color.WHITE);
    }//GEN-LAST:event_maximizebtnMouseExited

    private void minimizebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizebtnMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(this.ICONIFIED);
    }//GEN-LAST:event_minimizebtnMouseClicked

    private void minimizebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizebtnMouseEntered
        // TODO add your handling code here:
        minimizebtn.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_minimizebtnMouseEntered

    private void minimizebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizebtnMouseExited
        // TODO add your handling code here:
        minimizebtn.setBackground(Color.WHITE);
    }//GEN-LAST:event_minimizebtnMouseExited

    private void sugarcomboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sugarcomboboxItemStateChanged
        // TODO add your handling code here:
        priceload();
    }//GEN-LAST:event_sugarcomboboxItemStateChanged

    private void toppingcomboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_toppingcomboboxItemStateChanged
        // TODO add your handling code here:
        priceload();
    }//GEN-LAST:event_toppingcomboboxItemStateChanged

    
    private void addbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMouseClicked
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/possystem?zeroDateTimeBehavior=CONVERT_TO_NULL";
        String user = "root";
        String password = "root";
        
        
            try {
                Connection connection = DriverManager.getConnection(url, user, password);
                String query = "Select * from items where ID = "+getid+"";
                try (PreparedStatement preparedStatement = connection.prepareStatement(query); ResultSet resultSet = preparedStatement.executeQuery()) {
                    while(resultSet.next()){
                    qty = resultSet.getInt("qty");
                   
                    System.out.println(qty);
                    if(qty>0){
                        String query1 = "Insert into tempdata(itemsname,price,type,Sugar,Ice,Topping)values(?,?,?,?,?,?)";
                        PreparedStatement preparedStatement1 = connection.prepareStatement(query1);
                        preparedStatement1.setString(1, itemname);
                        preparedStatement1.setString(2, totalpricelabel.getText());
                        preparedStatement1.setString(3, cupsizelabel);
                        preparedStatement1.setString(4, sugarcombobox.getSelectedItem().toString());
                        preparedStatement1.setString(5, icecombobox.getSelectedItem().toString());
                        preparedStatement1.setString(6, toppingcombobox.getSelectedItem().toString());
                        
                        preparedStatement1.execute();
                        
                        qty = qty - 1;
                        String query2 = "Update items set qty =? where ID = "+getid+"";
                        PreparedStatement preparedStatement2 = connection.prepareStatement(query2);
                        preparedStatement2.setInt(1, qty);
                        System.out.println(qty);
                        preparedStatement2.executeUpdate();
                    }else{
                    JOptionPane.showMessageDialog(null,"Out of stock");
                    }
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(itemselect.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_addbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(itemselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(itemselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(itemselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(itemselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new itemselect().setVisible(true);
            }
        });
    }
    public void imageload(){
        ImageIcon closeicon = new ImageIcon(this.getClass().getResource("../icon/close.png"));
        Image logoclose = closeicon.getImage();
        Image scaleclose = logoclose.getScaledInstance(15,15,Image.SCALE_SMOOTH);
        ImageIcon scaledclose = new ImageIcon(scaleclose);
        closebtn.setIcon(scaledclose); 
        
        ImageIcon maximizeicon = new ImageIcon(this.getClass().getResource("../icon/maximize.png"));
        Image logomaximize = maximizeicon.getImage();
        Image scalemaximize = logomaximize.getScaledInstance(15,15,Image.SCALE_SMOOTH);
        ImageIcon scaledmaximize = new ImageIcon(scalemaximize);
        maximizebtn.setIcon(scaledmaximize); 
        
        ImageIcon minimizeicon = new ImageIcon(this.getClass().getResource("../icon/minimize.png"));
        Image logominimize = minimizeicon.getImage();
        Image scaleminimize = logominimize.getScaledInstance(15,15,Image.SCALE_SMOOTH);
        ImageIcon scaledminimize = new ImageIcon(scaleminimize);
        minimizebtn.setIcon(scaledminimize);
        
        ImageIcon cupicon = new ImageIcon(this.getClass().getResource("../icon/cup_size.png"));
        Image logocup = cupicon.getImage();
        Image scalecup1 = logocup.getScaledInstance(25,50,Image.SCALE_SMOOTH);
        ImageIcon scaledcup1 = new ImageIcon(scalecup1);
        ventibtn.setIcon(scaledcup1); 
        
        Image scalecup2 = logocup.getScaledInstance(25,40,Image.SCALE_SMOOTH);
        ImageIcon scaledcup2 = new ImageIcon(scalecup2);
        grandebtn.setIcon(scaledcup2); 
        
        Image scalecup3 = logocup.getScaledInstance(25,30,Image.SCALE_SMOOTH);
        ImageIcon scaledcup3 = new ImageIcon(scalecup3);
        tallbtn.setIcon(scaledcup3); 
        
        Image scalecup4 = logocup.getScaledInstance(20,20,Image.SCALE_SMOOTH);
        ImageIcon scaledcup4 = new ImageIcon(scalecup4);
        shortbtn.setIcon(scaledcup4); 
    }
    
    public void cupsizecolor(){
        String cupsizecolor = cupsizelabel;
        
        if (null == cupsizecolor) {   
        } else switch (cupsizelabel) {
            case "Venti" -> {
                ventibtn.setBackground(Color.green);
                grandebtn.setBackground(Color.white);
                tallbtn.setBackground(Color.white);
                shortbtn.setBackground(Color.white);
            }
            case "Grande" -> {
                grandebtn.setBackground(Color.green);
                ventibtn.setBackground(Color.white);
                tallbtn.setBackground(Color.white);
                shortbtn.setBackground(Color.white);
            }
            case "Tall" -> {
                tallbtn.setBackground(Color.green);
                ventibtn.setBackground(Color.white);
                grandebtn.setBackground(Color.white);
                shortbtn.setBackground(Color.white);
            }
            case "Short" -> {   
                shortbtn.setBackground(Color.green);
                ventibtn.setBackground(Color.white);
                grandebtn.setBackground(Color.white);
                tallbtn.setBackground(Color.white);
            }
            default -> {
            }
        }       
    }             
    public void priceload(){
        double cupprice = 0;
        
        String cupsizecolor = cupsizelabel;
        switch (cupsizecolor) {
            case "Venti" ->
                cupprice = 5000;
            case "Grande" ->
                cupprice = 4000;
            case "Tall" ->
                cupprice = 3000;
            case "Short" ->
                cupprice = 2000;
        }
        double sugarprice = 0;
        int sugar = sugarcombobox.getSelectedIndex();
        switch (sugar) {
            case 1 ->
                sugarprice = 200;
            case 2 ->
                sugarprice = 300;      
        }
        double toppingprice = 0;
        int topping = toppingcombobox.getSelectedIndex();
        switch(topping){
            case 1 ->
                toppingprice = 1000;
            case 2 ->
                toppingprice = 300;
            case 3 ->
                toppingprice = 400;
            case 4 ->
                toppingprice = 500;
            case 5 ->
                toppingprice = 600;
        }
        double total =baseprice+ cupprice + sugarprice + toppingprice;
        totalpricelabel.setText(total +"Kyat");
        System.out.println(total);
    }

    public void dataload(DataHolder dataHolder){   
        itemlabel.setText("<html>" + dataHolder.getitemnamedata() + "</html>");
        ImageIcon itemimg = new ImageIcon(getClass().getResource("../images/" + dataHolder.getitemimgdata()));
        Image logoitem = itemimg.getImage();
        Image scaleitem = logoitem.getScaledInstance(120, 137, Image.SCALE_SMOOTH);
        ImageIcon scaleditem = new ImageIcon(scaleitem);
        itemimglabel.setIcon(scaleditem);  
        String itemtype = dataHolder.itemtypedata();
        String itemtype2 = dataHolder.itemtyp2data();
        String[] itemtypeholder = new String[]{"Hot Coffees","Hot Teas","Hot Drinks"};
        if(Arrays.asList(itemtypeholder).contains(itemtype2)){
            System.out.println("match");
            icecombobox.setEnabled(false);
        }
        itemname = dataHolder.getitemnamedata();
        getid = dataHolder.getItemIDdata();
        baseprice = dataHolder.basepricedata();
        System.out.println(dataHolder.basepricedata());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customframework.Button addbtn;
    private javax.swing.JLabel closebtn;
    private customframework.ButtonCircle grandebtn;
    private javax.swing.JComboBox<String> icecombobox;
    private javax.swing.JLabel itemimglabel;
    private javax.swing.JLabel itemlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel maximizebtn;
    private javax.swing.JLabel minimizebtn;
    private customframework.PanelRound panelRound1;
    private customframework.ButtonCircle shortbtn;
    private javax.swing.JComboBox<String> sugarcombobox;
    private customframework.ButtonCircle tallbtn;
    private javax.swing.JComboBox<String> toppingcombobox;
    private javax.swing.JLabel totalpricelabel;
    private customframework.ButtonCircle ventibtn;
    // End of variables declaration//GEN-END:variables
}
